### ISSUE TITLE
Job submission feature requests

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#158]
Job Queue still has some problems to be solved:
- [ ] (! Important) Fix job execution order. (ray seems not preserving the FIFO order of the job queue). [submitted to ray issue](https://github.com/ray-project/ray/issues/21797) (@mraheja had a prototype of the scheduler [here](https://github.com/ray-project/ray/pull/22338/files))
  ```bash
  Sky Job Queue of Cluster test2
  +-----+------+------------+-----------+-----------------------------------------+
  | JOB | USER | SUBMITTED  |   STATUS  | LOG                                     |
  +-----+------+------------+-----------+-----------------------------------------+
  | 103 | zhwu | 2 mins ago |  PENDING  | sky_logs/sky-2022-01-06-02-36-36-737105 |
  | 105 | zhwu | 1 min ago  |  RUNNING  | sky_logs/sky-2022-01-06-02-37-03-308653 |
  | 104 | zhwu | 1 min ago  |  RUNNING  | sky_logs/sky-2022-01-06-02-36-50-699314 |
  | 102 | zhwu | 2 mins ago | SUCCEEDED | sky_logs/sky-2022-01-06-02-36-23-662007 |
  | 101 | zhwu | 2 mins ago | SUCCEEDED | sky_logs/sky-2022-01-06-02-36-06-512089 |
  +-----+------+------------+-----------+-----------------------------------------+
  ```
  Note: it seems that FIFO is an expected feature of ray, and they are trying to patch it, according to Eric. However, it may take a while for ray to fix it and publish it in the release version. Here are two possible workarounds that remain to be investigated:
  1. The placement_group manager used in the ray.tune
  2. Manually do the scheduling the placement group by storing scheduling states in the job database (as mentioned by Romil).
- [ ] ~~Launching cluster for a task with `K80: 0.5` should round to `K80: 1`~~.
- [x] Job requested resources  / duration in the job queue #729 
- [x] Fix executing job with num_nodes=2 on a cluster with 3 nodes. (This is blocked by the `post_setup_fn` design for distributed training). #255 
- [x] #262. Fixed in #261 and submitted a PR to ray [here](https://github.com/ray-project/ray/pull/21977).
- [x] Job name in the job queue. #196 
- [x] `sky logs -c cluster job --sync-down` to sync down the logs to local for multi-node application. [#196]
- [x] Fix logs auto-ending with the status from `ray job status`. [Fixed in #159.]
- [x] `sky queue` shows all the jobs by default. (from zongheng). [Fixed in #159.]
- [x] misalignment of \t going on. (from zongheng). [Fixed in #159.]
```bash
I 01-10 09:31:39 cloud_vm_ray_backend.py:1216] NOTE: ctrl-c does not stop the job.
I 01-10 09:31:39 cloud_vm_ray_backend.py:1216]
I 01-10 09:31:39 cloud_vm_ray_backend.py:1216] Job ID: 1
I 01-10 09:31:39 cloud_vm_ray_backend.py:1216] To cancel the job:       sky cancel -c min 1
I 01-10 09:31:39 cloud_vm_ray_backend.py:1216] To stream logs:  sky logs -c min 1
I 01-10 09:31:39 cloud_vm_ray_backend.py:1216] To view the job queue:   sky queue -c min
I 01-10 09:31:39 cloud_vm_ray_backend.py:1368]
I 01-10 09:31:39 cloud_vm_ray_backend.py:1368] Cluster name: min
I 01-10 09:31:39 cloud_vm_ray_backend.py:1368] To log into the head VM: sky ssh min
I 01-10 09:31:39 cloud_vm_ray_backend.py:1368] To submit job to the cluster:    sky exec -c min yaml_file
I 01-10 09:31:39 cloud_vm_ray_backend.py:1368] To teardown the cluster: sky down min
I 01-10 09:31:39 cloud_vm_ray_backend.py:1368] To stop the cluster:     sky stop min
```

**Comment by Michaelvll** [comment]
The last remaining request will be solved by #1636.
