### ISSUE TITLE
[Lambda Cloud] Umbrella ticket for future TODOs

### ISSUE THREAD

**Issue by ewzeng** [skypilot-org/skypilot#1647]
#### Multi-node support 
- [x] Done (implemented in #1718)

#### Script to update catalog
- [x] Done ( implemented in #1722)

#### Lambda in `sky gpunode`
- [ ] Done

`sky gpunode` doesn't list Lambda Cloud because Lambda Cloud does not have any K80 instances. There are two possible solutions to this problem:

- Ignore it. Currently `sky gpunode` is the same as `sky launch --gpus K80:1`, so getting Lambda listed in `sky gpunode` will make the logic (significantly) more complicated.
- Fix it.

#### `LambdaNodeProvider` tag file synchronization
- [ ] Done

We should add file locks to the tag file (good practice, even if we already have ray-related synchronization).

#### Implement `get_current_user_identity`
- [ ] Done

#### Handle `Ctrl-C` after launch
- [x] Done (fixed by #1718)

#### Update docs
- [x] Done (updated in #1659)

#### Recursive `sky launch` support
- [x] Done (fixed in #1838)
