### ISSUE TITLE
[100 jobs] Abnormal failover leading to duplicate instances

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#656]
Milestone "100 jobs": Launch 100 jobs, each taking its own cluster.

```bash
#!/bin/bash
set -ex
for i in $(seq 100); do
    sky launch -y -d --cloud=aws -c node-"$i" --gpus=K80 >node-"$i".log 2>&1 -- "gpustat; echo node $i"  &
    sleep 2
done
wait
sky autostop --all
```

----

Console shows all 90 VMs are Running.  However, sky status shows ~19 UP (successfully finished the command), the rest all INIT (failed).  

One type of failures is weird:
```
I 03-27 11:30:08 cloud_vm_ray_backend.py:952] Launching on AWS us-east-1 (us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e,us-east-1f)
I 03-27 11:31:29 log_lib.py:37] Head node is up.
W 03-27 11:33:09 cloud_vm_ray_backend.py:542] Got error(s) in all zones of us-east-1:
W 03-27 11:33:09 cloud_vm_ray_backend.py:544]   2022-03-27 11:30:23,714 WARN node_provider.py:444 -- create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient p2.xlarge capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get p2.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1b, us-east-1c, us-east-1d, us-east-1e., retrying.
I 03-27 11:36:38 cloud_vm_ray_backend.py:952] Launching on AWS us-east-2 (us-east-2a,us-east-2b,us-east-2c)
W 03-27 11:36:54 cloud_vm_ray_backend.py:542] Got error(s) in all zones of us-east-2:
...
I 03-27 11:37:11 cloud_vm_ray_backend.py:535] ====== stderr ======
2022-03-27 11:37:01,945 INFO util.py:282 -- setting max workers for head node type to 0
2022-03-27 11:37:11,008 PANIC config.py:665 -- Failed to create security group
```
- [x] (Solved by #661)  It shows us-east-1a failed. Console shows this node is launched in us-east-1b.  So we should not have failed over to us-east-2.
- [ ] After “failing over” to us-east-2, `Failed to create security group` shown.  This error happens again (see the 1st comment below).

- [x] (Solved by #657) Another type of failures is wheel builds -- even with locking already added -- overwrite each other.  15 nodes have this failure.
```
file has vanished: "/var/folders/8f/56gzvwkd3n3293xjlrztr6600000gp/T/sky_wheels_zongheng/sky.egg-info/top_level.txt"
...
rsync warning: some files vanished before they could be transferred (code 24) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.
120.1/rsync/main.c(996) [sender=2.6.9]
```

- [x] (No longer triggers with #657 merged ) Final result is resource leak:  Console shows duplicate nodes launched in 3 regions: east-1 (90), east-2 (19), west-2 (51).   There should be in total 90 instances according to the script.

- [ ] Lots of runs print `create_instances: Attempt failed with An error occurred (RequestLimitExceeded) when calling the RunInstances operation (reached max retries: 0): Request limit exceeded., retrying.`.  We should add randomized backoff, potentially.

- [ ] (Orthogonal/related) When launching 90 in parallel, laptop will be pretty oversubscribed.  To solve this we need async provisioning / send these launches to a service (can be a skylet server running locally that queues these provisioning requests).

- [x] (Mitigated by #731 as we use a few shared SGs now) (Orthogonal/related) ray down doesn't delete the security groups created. My num security group limit is 2500 per region, and I now have 200-400 SGs per region.

- [ ] sqlite3.OperationalError: database is locked

**Comment by concretevitamin** [comment]
With the latest master commit d41cf2f57b81c:

Using the repro in https://github.com/skypilot-org/skypilot/issues/656#issuecomment-1152955322 to launch 100 spot jobs:
- [ ] TODO: 98 jobs succeeded, 2 encountered 
```
I 10-11 16:52:22 cloud_vm_ray_backend.py:996] Successfully provisioned or found existing VM.
...
  File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/backends/backend.py", line 50, in provision
    cluster_name, retry_until_up)
  File "/Users/zongheng/Dropbox/workspace/riselab/sky-computing/sky/backends/cloud_vm_ray_backend.py", line 1848, in _provision
    os.remove(lock_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zongheng/.sky/.sky-spot-controller-8a3968f2.lock'
```

Took ~1 hour for 98 jobs (1.6 spot job per minute).

**Comment by concretevitamin** [comment]
With the latest master commit d41cf2f57b81c14f89b500febe93da4df4a27173, launching 100 on-demand jobs concurrently still has problems, resulting in 71 clusters launched out of 100.

**Comment by Michaelvll** [comment]
With the #1218, launching 100 spot jobs should be easier. Testing:
- [ ] Following script
```
#!/bin/bash
set -ex
for i in $(seq 100); do
    sky spot launch -y -d --cloud=aws -n n4-"$i" >node-"$i".log 2>&1 -- 'echo node $i, $(hostname)'  &
done
wait
```

**Comment by concretevitamin** [comment]
Trying this stress test again on 4e227cef: not successful, laptop OOM'd about 1 hour in (with lots of other apps like Chrome).
