### ISSUE TITLE
[Managed Spot] Features required in the managed spot

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#771]
### Future TODOs:
- [x] #799
- [ ] #800
- [x] #865
- [ ] Better loggings for the spot controller outputs
- [x] Examples: Test real resnet training with spot launch
- [ ] Reduce the number of jobs to be shown in the `sky spot status` by default.
- [x] Design tests
- [x] #845
- [x] Multi-node spot job.
- [ ] Currently, we can only launch 2xCPU in spot controller instance, as our controllers are submitted as sky jobs (each takes 0.5 CPU by default).
- [x] There will be a worker launched after the head node is killed even for the single-node case. It may be related to the ray autoscaling. (This should have been solved by #780)
- [x] #790
- [x] #774
- [x] #777
- [x] #778
- [x] Error out on cancel if the controller has already abnormally exited its control loop. (https://github.com/sky-proj/sky/issues/771#issuecomment-1118124565) (#784)

### Requested features
- [ ] Show detailed provision/setup logs for the user in `sky spot logs`. (https://github.com/sky-proj/sky/pull/798#issuecomment-1120221669) (We can use archive logs #800)
- [x] Remove STARTED column and add complete resource str in `sky spot status -a` (https://github.com/sky-proj/sky/issues/771#issuecomment-1120115106) (Fixed by #823)
- [ ] Make RECOVERIES column: 0 (1 attempt), 2 (2 attempts) (https://github.com/sky-proj/sky/issues/771#issuecomment-1118124565)
- [x] #828 
- [ ] Show region and resources information afterthe job finished. (https://github.com/sky-proj/sky/issues/771#issuecomment-1126542448)
- [x] #861 
        (https://github.com/sky-proj/sky/issues/771#issuecomment-1118124565)
- [x] #1073
